# Generated by Django 4.2.9 on 2026-04-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_knowledgedocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_d_role_sc_243467_idx',
            old_name='knowledge_d_role_sc_1e66b0_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_d_parse_s_b79af0_idx',
            old_name='knowledge_d_parse_s_6f710d_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_i_categor_b348f1_idx',
            old_name='knowledge_it_categor_62c4b8_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_i_role_sc_8bf22f_idx',
            old_name='knowledge_it_role_sc_fc4df9_idx',
        ),
        migrations.RenameIndex(
            model_name='qalog',
            new_name='qa_logs_role_77fda7_idx',
            old_name='qa_logs_role_92c5ba_idx',
        ),
        migrations.RenameIndex(
            model_name='qalog',
            new_name='qa_logs_success_532d99_idx',
            old_name='qa_logs_success_3d487c_idx',
        ),
    ]
