# Generated by Django 4.2.9 on 2026-04-13 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('suggestion', '功能建议'), ('issue', '使用问题'), ('complaint', '投诉'), ('other', '其他')], default='other', max_length=30, verbose_name='类别')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, help_text='可填手机号/邮箱/微信等，便于联系', max_length=100, null=True, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('new', '新提交'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='new', max_length=20, verbose_name='状态')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '系统反馈',
                'verbose_name_plural': '系统反馈',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='feedbacks_status_e7bc93_idx'), models.Index(fields=['user', 'created_at'], name='feedbacks_user_id_c7b83f_idx')],
            },
        ),
    ]
