# Generated by Django 4.2.9 on 2026-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介', null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, help_text='所属校区', max_length=50, null=True, verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='user',
            name='class_number',
            field=models.CharField(blank=True, help_text='班级编号', max_length=50, null=True, verbose_name='班号'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, help_text='用户真实姓名', max_length=50, null=True, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, help_text='所属学校', max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='学生学号', max_length=20, null=True, verbose_name='学号'),
        ),
    ]
