# Generated by Django 4.2.9 on 2026-02-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0002_storedfile'),
        ('accounts', '0002_user_bio_user_campus_user_class_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False表示账号已禁用', verbose_name='账号状态'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', '创建用户'), ('update_user', '更新用户'), ('delete_user', '删除用户'), ('reset_password', '重置密码'), ('toggle_status', '切换状态'), ('assign_order', '派单'), ('update_order_status', '更新工单状态'), ('batch_enable', '批量启用'), ('batch_disable', '批量禁用'), ('batch_delete', '批量删除')], max_length=50, verbose_name='操作类型')),
                ('description', models.TextField(blank=True, help_text='详细描述操作内容', verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('target_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repairs.workorder', verbose_name='目标工单')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_logs', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '用户日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator'], name='operation_l_operato_b6afa6_idx'), models.Index(fields=['action'], name='operation_l_action_23516c_idx'), models.Index(fields=['created_at'], name='operation_l_created_3fec78_idx')],
            },
        ),
    ]
