"""
Django settings for dormfix_backend project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 从项目根目录的 .env 加载环境变量（如 DB_PASSWORD）
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yo$qinxz)#1@_3ap$y-bfvm=tytkh%1n#e)!&fv6#i#p0u*5c7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',  # SimpleUI 必须放在第一位
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'accounts',
    'repairs',
    'announcements',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dormfix_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dormfix_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# 默认用 SQLite，无需配置密码即可运行。配好 .env 的 DB_PASSWORD 后改用下方 MySQL 即可。
USE_MYSQL = os.environ.get('DB_PASSWORD', '').strip() != ''

if USE_MYSQL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'DormFix',
            'USER': 'root',
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': 'localhost',
            'PORT': '3306',
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 中文

TIME_ZONE = 'Asia/Shanghai'  # 中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Media files：上传文件存入数据库，不占本地磁盘，便于部署到平台
MEDIA_URL = '/media/'
# 默认文件存储改为数据库（repairs.StoredFile），不再使用本地 media 目录
STORAGES = {
    'default': {
        'BACKEND': 'repairs.storage_db.DatabaseStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# CORS 配置（开发环境）
CORS_ALLOW_ALL_ORIGINS = True  # 生产环境需要改为具体域名
CORS_ALLOW_CREDENTIALS = True

# 前端开发时在 5173，POST 需通过 CSRF；生产环境按实际域名改
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Session Cookie 配置（开发环境跨域）
SESSION_COOKIE_SAMESITE = 'Lax'  # 允许跨域携带 cookie
SESSION_COOKIE_SECURE = False  # 开发环境使用 HTTP
SESSION_COOKIE_HTTPONLY = True  # 防止 XSS 攻击
SESSION_COOKIE_AGE = 86400  # 24小时

# CSRF Cookie 配置
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False  # 前端需要读取 CSRF token

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# SimpleUI 配置
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'  # 主题
SIMPLEUI_HOME_INFO = True  # 显示首页信息
SIMPLEUI_HOME_QUICK = True  # 显示快速操作
SIMPLEUI_HOME_ACTION = True  # 显示最近动作

# SimpleUI 首页配置
SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'  # 可以改成自己的首页
SIMPLEUI_HOME_TITLE = 'DormFix 宿舍报修系统'
SIMPLEUI_HOME_ICON = 'fa fa-home'

# SimpleUI Logo
SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4'

# 隐藏右侧SimpleUI广告
SIMPLEUI_HOME_INFO = False

# 自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,  # 不保留系统菜单
    'menu_display': ['用户管理', '报修管理', '系统设置'],  # 开启排序和过滤功能
    'dynamic': True,  # 设置是否开启动态菜单
    'menus': [
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fa fa-user',
                    'url': 'accounts/user/'
                }
            ]
        },
        {
            'name': '报修管理',
            'icon': 'fas fa-tools',
            'models': [
                {
                    'name': '工单管理',
                    'icon': 'fa fa-clipboard-list',
                    'url': 'repairs/workorder/'
                },
                {
                    'name': '故障类型',
                    'icon': 'fa fa-tags',
                    'url': 'repairs/repairtype/'
                },
                {
                    'name': '工单日志',
                    'icon': 'fa fa-history',
                    'url': 'repairs/orderlog/'
                },
                {
                    'name': '评价管理',
                    'icon': 'fa fa-star',
                    'url': 'repairs/comment/'
                }
            ]
        }
    ]
}
